In [1]:
import pandas as pd
import json
import numpy as np

In [31]:
df = pd.read_csv('../data/sources/WeimarDB/wjazzd_manual_chords.csv')

In [32]:
df

,beatid,melid,onset,bar,beat,signature,chord,form,bass_pitch,chorus_id
0,6285,27,2.473469,0,4,NaN,NC,I1,37,0
1,6286,27,2.832653,1,1,4/4,Eb,A1,40,1
2,6287,27,3.172766,1,2,NaN,NaN,NaN,39,1
3,6288,27,3.485238,1,3,NaN,NaN,NaN,37,1
4,6289,27,3.818186,1,4,NaN,NaN,NaN,37,1
...,...,...,...,...,...,...,...,...,...,...
973,71768,231,116.967415,129,4,NaN,NaN,NaN,35,5
974,71769,231,117.187732,130,1,NaN,C-7,NaN,36,5
975,71770,231,117.408050,130,2,NaN,NaN,NaN,34,5
976,71771,231,117.639229,130,3,NaN,F7,NaN,34,5
977,71772,231,117.851791,130,4,NaN,NaN,NaN,42,5

In [33]:
margie = df[df['melid'] == 27].reset_index()
margie

,index,beatid,melid,onset,bar,beat,signature,chord,form,bass_pitch,chorus_id
0,0,6285,27,2.473469,0,4,NaN,NC,I1,37,0
1,1,6286,27,2.832653,1,1,4/4,Eb,A1,40,1
2,2,6287,27,3.172766,1,2,NaN,NaN,NaN,39,1
3,3,6288,27,3.485238,1,3,NaN,NaN,NaN,37,1
4,4,6289,27,3.818186,1,4,NaN,NaN,NaN,37,1
...,...,...,...,...,...,...,...,...,...,...,...
63,63,6348,27,23.444898,16,3,NaN,NaN,NaN,42,1
64,64,6349,27,23.797800,16,4,NaN,NaN,NaN,40,1
65,65,6350,27,24.111179,17,1,NaN,Eb,I1,40,1
66,66,6351,27,24.453016,17,2,NaN,NaN,NaN,39,1
67,67,6352,27,24.810726,17,3,NaN,NaN,NaN,37,1

In [34]:
oleo = df[df['melid'] == 231].reset_index()
oleo

,index,beatid,melid,onset,bar,beat,signature,chord,form,bass_pitch,chorus_id
0,458,71253,231,0.860680,1,1,4/4,Bbj7,A1,38,1
1,459,71254,231,1.094399,1,2,NaN,NaN,NaN,36,1
2,460,71255,231,1.327234,1,3,NaN,G7,NaN,35,1
3,461,71256,231,1.551383,1,4,NaN,NaN,NaN,38,1
4,462,71257,231,1.774739,2,1,NaN,C-7,NaN,36,1
...,...,...,...,...,...,...,...,...,...,...,...
515,973,71768,231,116.967415,129,4,NaN,NaN,NaN,35,5
516,974,71769,231,117.187732,130,1,NaN,C-7,NaN,36,5
517,975,71770,231,117.408050,130,2,NaN,NaN,NaN,34,5
518,976,71771,231,117.639229,130,3,NaN,F7,NaN,34,5
519,977,71772,231,117.851791,130,4,NaN,NaN,NaN,42,5

In [35]:
blue = df[df['melid'] == 218].reset_index()
blue

,index,beatid,melid,onset,bar,beat,signature,chord,form,bass_pitch,chorus_id
0,68,60418,218,2.285714,0,1,NaN,NC,I1,39,0
1,69,60419,218,2.677551,0,2,NaN,NaN,NaN,37,0
2,70,60420,218,3.077551,0,3,NaN,NaN,NaN,36,0
3,71,60421,218,3.506122,0,4,NaN,NaN,NaN,36,0
4,72,60422,218,3.926531,1,1,4/4,Eb7,A1,38,1
...,...,...,...,...,...,...,...,...,...,...,...
385,453,60803,218,165.648980,96,2,NaN,NaN,NaN,35,8
386,454,60804,218,166.059819,96,3,NaN,NaN,NaN,36,8
387,455,60805,218,166.501406,96,4,NaN,NaN,NaN,38,8
388,456,60806,218,166.948526,97,1,NaN,Eb7,A1,43,9
389,457,60807,218,167.405465,97,2,NaN,NaN,NaN,38,9

In [40]:
margie['step'] = (margie['bar'] - 1) * 4 + (margie['beat'] - 1)
oleo['step'] = (oleo['bar'] - 1) * 4 + (oleo['beat'] - 1)
blue['step'] = (blue['bar'] - 1) * 4 + (blue['beat'] - 1)

In [46]:
margie[['bar', 'beat', 'step', 'chord']]

    bar  beat  step chord
0     0     4    -1    NC
1     1     1     0    Eb
2     1     2     1   NaN
3     1     3     2   NaN
4     1     4     3   NaN
..  ...   ...   ...   ...
63   16     3    62   NaN
64   16     4    63   NaN
65   17     1    64    Eb
66   17     2    65   NaN
67   17     3    66   NaN

[68 rows x 4 columns]

In [44]:
blue[['bar', 'beat', 'step', 'chord']]

     bar  beat  step chord
0      0     1    -4    NC
1      0     2    -3   NaN
2      0     3    -2   NaN
3      0     4    -1   NaN
4      1     1     0   Eb7
..   ...   ...   ...   ...
385   96     2   381   NaN
386   96     3   382   NaN
387   96     4   383   NaN
388   97     1   384   Eb7
389   97     2   385   NaN

[390 rows x 4 columns]

In [45]:
oleo[['bar', 'beat', 'step', 'chord']]

     bar  beat  step chord
0      1     1     0  Bbj7
1      1     2     1   NaN
2      1     3     2    G7
3      1     4     3   NaN
4      2     1     4   C-7
..   ...   ...   ...   ...
515  129     4   515   NaN
516  130     1   516   C-7
517  130     2   517   NaN
518  130     3   518    F7
519  130     4   519   NaN

[520 rows x 4 columns]

In [68]:
sections = []
parts = {}

current_part = None
current_chord = None

for i, r in margie.iterrows():
    form = r['form']
    chord = r['chord']
    
    if type(form) == str:
        sections.append(form)
        current_part = form
        
        parts[form] = []
    
    if type(chord) == str:
        current_chord = chord
        parts[current_part].append(chord)
    else:
        parts[current_part].append(current_chord)
    
    print(form, chord, current_part, current_chord)

I1 NC I1 NC
A1 Eb A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan Eb7 A1 Eb7
nan nan A1 Eb7
nan nan A1 Eb7
nan nan A1 Eb7
nan Ab A1 Ab
nan nan A1 Ab
nan nan A1 Ab
nan nan A1 Ab
nan nan A1 Ab
nan nan A1 Ab
nan nan A1 Ab
nan nan A1 Ab
nan G7 A1 G7
nan nan A1 G7
nan nan A1 G7
nan nan A1 G7
nan nan A1 G7
nan nan A1 G7
nan nan A1 G7
nan nan A1 G7
nan Eb A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan Eb7 A1 Eb7
nan D7 A1 D7
nan Db7 A1 Db7
nan C7 A1 C7
nan nan A1 C7
nan nan A1 C7
nan nan A1 C7
nan F-7 A1 F-7
nan nan A1 F-7
nan nan A1 F-7
nan nan A1 F-7
nan Bb7 A1 Bb7
nan nan A1 Bb7
nan nan A1 Bb7
nan nan A1 Bb7
nan Eb A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan nan A1 Eb
nan Bb7 A1 Bb7
nan nan A1 Bb7
nan nan A1 Bb7
nan nan A1 Bb7
I1 Eb I1 Eb
nan nan I1 Eb
nan nan I1 Eb

In [89]:
sections = ['A1']

In [92]:
parts = {'A1': parts['A1']}
parts

{'A1': ['Eb',
  'Eb',
  'Eb',
  'Eb',
  'Eb',
  'Eb',
  'Eb',
  'Eb',
  'Eb',
  'Eb',
  'Eb',
  'Eb',
  'Eb7',
  'Eb7',
  'Eb7',
  'Eb7',
  'Ab',
  'Ab',
  'Ab',
  'Ab',
  'Ab',
  'Ab',
  'Ab',
  'Ab',
  'G7',
  'G7',
  'G7',
  'G7',
  'G7',
  'G7',
  'G7',
  'G7',
  'Eb',
  'Eb',
  'Eb',
  'Eb',
  'Eb',
  'Eb',
  'Eb',
  'Eb',
  'Eb',
  'Eb7',
  'D7',
  'Db7',
  'C7',
  'C7',
  'C7',
  'C7',
  'F-7',
  'F-7',
  'F-7',
  'F-7',
  'Bb7',
  'Bb7',
  'Bb7',
  'Bb7',
  'Eb',
  'Eb',
  'Eb',
  'Eb',
  'Bb7',
  'Bb7',
  'Bb7',
  'Bb7']}

In [84]:
chord_prog = {}

In [93]:
chord_prog['Margie'] = {
    'section': sections,
    'progression': parts,
    "key": "Eb",
    "minor": False,
    "time_signature": [4,4]
}

In [95]:
sections_o = []
parts_o = {}

current_part = None
current_chord = None

for i, r in oleo.iterrows():
    form = r['form']
    chord = r['chord']
    
    if type(form) == str:
        sections_o.append(form)
        current_part = form
        
        parts_o[form] = []
    
    if type(chord) == str:
        current_chord = chord
        parts_o[current_part].append(chord)
    else:
        parts_o[current_part].append(current_chord)
    
#     print(form, chord, current_part, current_chord)

A1 Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C- A1 C-
nan nan A1 C-
nan F7 A1 F7
nan nan A1 F7
nan F-7 A1 F-7
nan nan A1 F-7
nan Bb7 A1 Bb7
nan nan A1 Bb7
nan Ebj7 A1 Ebj7
nan nan A1 Ebj7
nan Eb-6 A1 Eb-6
nan nan A1 Eb-6
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
A2 Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan C-7 A2 C-7
nan nan A2 C-7
nan F7 A2 F7
nan nan A2 F7
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan C-7 A2 C-7
nan nan A2 C-7
nan F7 A2 F7
nan nan A2 F7
nan F-7 A2 F-7
nan nan A2 F-7
nan Bb7 A2 Bb7
nan nan A2 Bb7
nan Ebj7 A2 Ebj7
nan nan A2 Ebj7
nan Eb-6 A2 Eb-6
nan nan A2 Eb-6
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan nan A2 Bbj7
nan nan A2 Bbj7
B1 D7 B1 D7
nan nan B1 D7
nan nan B1 D7
nan nan B1 D7
nan D7 B1 D7
nan nan B1 D7
nan nan B1 D7
nan nan B1 D7
nan G7 B1 G7
nan nan B1 G7
nan nan B1 G7
nan nan B1 G7
nan G7 B1 G7
nan nan B1 G7
nan nan B1 G7
nan nan B1 G7
nan C7 B1 C7
nan nan B1 C7
nan nan B1 C7
nan nan B1 C7
nan C7 B1 C7
nan nan B1 C7
nan nan B1 C7
nan nan B1 C7
nan F7 B1 F7
nan nan B1 F7
nan nan B1 F7
nan nan B1 F7
nan F7 B1 F7
nan nan B1 F7
nan nan B1 F7
nan nan B1 F7
A3 Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
nan Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
nan F-7 A3 F-7
nan nan A3 F-7
nan Bb7 A3 Bb7
nan nan A3 Bb7
nan Ebj7 A3 Ebj7
nan nan A3 Ebj7
nan Eb-6 A3 Eb-6
nan nan A3 Eb-6
nan Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
A1 Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
nan F-7 A1 F-7
nan nan A1 F-7
nan Bb7 A1 Bb7
nan nan A1 Bb7
nan Ebj7 A1 Ebj7
nan nan A1 Ebj7
nan Eb-6 A1 Eb-6
nan nan A1 Eb-6
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan nan A1 Bbj7
nan nan A1 Bbj7
A2 Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan C-7 A2 C-7
nan nan A2 C-7
nan F7 A2 F7
nan nan A2 F7
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan C-7 A2 C-7
nan nan A2 C-7
nan F7 A2 F7
nan nan A2 F7
nan F-7 A2 F-7
nan nan A2 F-7
nan Bb7 A2 Bb7
nan nan A2 Bb7
nan Ebj7 A2 Ebj7
nan nan A2 Ebj7
nan Eb-6 A2 Eb-6
nan nan A2 Eb-6
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan nan A2 Bbj7
nan nan A2 Bbj7
B1 D7 B1 D7
nan nan B1 D7
nan nan B1 D7
nan nan B1 D7
nan D7 B1 D7
nan nan B1 D7
nan nan B1 D7
nan nan B1 D7
nan G7 B1 G7
nan nan B1 G7
nan nan B1 G7
nan nan B1 G7
nan G7 B1 G7
nan nan B1 G7
nan nan B1 G7
nan nan B1 G7
nan C7 B1 C7
nan nan B1 C7
nan nan B1 C7
nan nan B1 C7
nan C7 B1 C7
nan nan B1 C7
nan nan B1 C7
nan nan B1 C7
nan F7 B1 F7
nan nan B1 F7
nan nan B1 F7
nan nan B1 F7
nan F7 B1 F7
nan nan B1 F7
nan nan B1 F7
nan nan B1 F7
A3 Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
nan Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
nan F-7 A3 F-7
nan nan A3 F-7
nan Bb7 A3 Bb7
nan nan A3 Bb7
nan Ebj7 A3 Ebj7
nan nan A3 Ebj7
nan Eb-6 A3 Eb-6
nan nan A3 Eb-6
nan Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
A1 Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
nan F-7 A1 F-7
nan nan A1 F-7
nan Bb7 A1 Bb7
nan nan A1 Bb7
nan Ebj7 A1 Ebj7
nan nan A1 Ebj7
nan Eb-6 A1 Eb-6
nan nan A1 Eb-6
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
A2 Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan C-7 A2 C-7
nan nan A2 C-7
nan F7 A2 F7
nan nan A2 F7
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan C-7 A2 C-7
nan nan A2 C-7
nan F7 A2 F7
nan nan A2 F7
nan nan A2 F7
nan nan A2 F7
nan Bb7 A2 Bb7
nan nan A2 Bb7
nan nan A2 Bb7
nan nan A2 Bb7
nan Eb-6 A2 Eb-6
nan nan A2 Eb-6
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan nan A2 Bbj7
nan nan A2 Bbj7
B1 D7 B1 D7
nan nan B1 D7
nan nan B1 D7
nan nan B1 D7
nan D7 B1 D7
nan nan B1 D7
nan nan B1 D7
nan nan B1 D7
nan G7 B1 G7
nan nan B1 G7
nan nan B1 G7
nan nan B1 G7
nan G7 B1 G7
nan nan B1 G7
nan nan B1 G7
nan nan B1 G7
nan C7 B1 C7
nan nan B1 C7
nan nan B1 C7
nan nan B1 C7
nan C7 B1 C7
nan nan B1 C7
nan nan B1 C7
nan nan B1 C7
nan F7 B1 F7
nan nan B1 F7
nan nan B1 F7
nan nan B1 F7
nan F7 B1 F7
nan nan B1 F7
nan nan B1 F7
nan nan B1 F7
A3 Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
nan Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
nan F-7 A3 F-7
nan nan A3 F-7
nan Bb7 A3 Bb7
nan nan A3 Bb7
nan Ebj7 A3 Ebj7
nan nan A3 Ebj7
nan Eb-6 A3 Eb-6
nan nan A3 Eb-6
nan Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
A1 Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
nan F-7 A1 F-7
nan nan A1 F-7
nan Bb7 A1 Bb7
nan nan A1 Bb7
nan Ebj7 A1 Ebj7
nan nan A1 Ebj7
nan Eb-6 A1 Eb-6
nan nan A1 Eb-6
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
A2 Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan C-7 A2 C-7
nan nan A2 C-7
nan F7 A2 F7
nan nan A2 F7
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan C-7 A2 C-7
nan nan A2 C-7
nan F7 A2 F7
nan nan A2 F7
nan F-7 A2 F-7
nan nan A2 F-7
nan Bb7 A2 Bb7
nan nan A2 Bb7
nan Ebj7 A2 Ebj7
nan nan A2 Ebj7
nan Eb-6 A2 Eb-6
nan nan A2 Eb-6
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan nan A2 Bbj7
nan nan A2 Bbj7
B1 D7 B1 D7
nan nan B1 D7
nan nan B1 D7
nan nan B1 D7
nan D7 B1 D7
nan nan B1 D7
nan nan B1 D7
nan nan B1 D7
nan G7 B1 G7
nan nan B1 G7
nan nan B1 G7
nan nan B1 G7
nan G7 B1 G7
nan nan B1 G7
nan nan B1 G7
nan nan B1 G7
nan C7 B1 C7
nan nan B1 C7
nan nan B1 C7
nan nan B1 C7
nan C7 B1 C7
nan nan B1 C7
nan nan B1 C7
nan nan B1 C7
nan F7 B1 F7
nan nan B1 F7
nan nan B1 F7
nan nan B1 F7
nan F7 B1 F7
nan nan B1 F7
nan nan B1 F7
nan nan B1 F7
A3 Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
nan Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
nan F-7 A3 F-7
nan nan A3 F-7
nan Bb7 A3 Bb7
nan nan A3 Bb7
nan Ebj7 A3 Ebj7
nan nan A3 Ebj7
nan Eb-6 A3 Eb-6
nan nan A3 Eb-6
nan Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
A1 Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7

In [99]:
chord_prog['Oleo'] = {
    'section': sections_o,
    'progression': parts_o,
    "key": "Bb",
    "minor": False,
    "time_signature": [4,4]
}

In [100]:
sections_b = []
parts_b = {}

current_part = None
current_chord = None

for i, r in oleo.iterrows():
    form = r['form']
    chord = r['chord']
    
    if type(form) == str:
        sections_b.append(form)
        current_part = form
        
        parts_b[form] = []
    
    if type(chord) == str:
        current_chord = chord
        parts_b[current_part].append(chord)
    else:
        parts_b[current_part].append(current_chord)
    
    print(form, chord, current_part, current_chord)

A1 Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C- A1 C-
nan nan A1 C-
nan F7 A1 F7
nan nan A1 F7
nan F-7 A1 F-7
nan nan A1 F-7
nan Bb7 A1 Bb7
nan nan A1 Bb7
nan Ebj7 A1 Ebj7
nan nan A1 Ebj7
nan Eb-6 A1 Eb-6
nan nan A1 Eb-6
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
A2 Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan C-7 A2 C-7
nan nan A2 C-7
nan F7 A2 F7
nan nan A2 F7
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan C-7 A2 C-7
nan nan A2 C-7
nan F7 A2 F7
nan nan A2 F7
nan F-7 A2 F-7
nan nan A2 F-7
nan Bb7 A2 Bb7
nan nan A2 Bb7
nan Ebj7 A2 Ebj7
nan nan A2 Ebj7
nan Eb-6 A2 Eb-6
nan nan A2 Eb-6
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan nan A2 Bbj7
nan nan A2 Bbj7
B1 D7 B1 D7
nan nan B1 D7
nan nan B1 D7
nan nan B1 D7
nan D7 B1 D7
nan nan B1 D7
nan nan B1 D7
nan nan B1 D7
nan G7 B1 G7
nan nan B1 G7
nan nan B1 G7
nan nan B1 G7
nan G7 B1 G7
nan nan B1 G7
nan nan B1 G7
nan nan B1 G7
nan C7 B1 C7
nan nan B1 C7
nan nan B1 C7
nan nan B1 C7
nan C7 B1 C7
nan nan B1 C7
nan nan B1 C7
nan nan B1 C7
nan F7 B1 F7
nan nan B1 F7
nan nan B1 F7
nan nan B1 F7
nan F7 B1 F7
nan nan B1 F7
nan nan B1 F7
nan nan B1 F7
A3 Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
nan Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
nan F-7 A3 F-7
nan nan A3 F-7
nan Bb7 A3 Bb7
nan nan A3 Bb7
nan Ebj7 A3 Ebj7
nan nan A3 Ebj7
nan Eb-6 A3 Eb-6
nan nan A3 Eb-6
nan Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
A1 Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
nan F-7 A1 F-7
nan nan A1 F-7
nan Bb7 A1 Bb7
nan nan A1 Bb7
nan Ebj7 A1 Ebj7
nan nan A1 Ebj7
nan Eb-6 A1 Eb-6
nan nan A1 Eb-6
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan nan A1 Bbj7
nan nan A1 Bbj7
A2 Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan C-7 A2 C-7
nan nan A2 C-7
nan F7 A2 F7
nan nan A2 F7
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan C-7 A2 C-7
nan nan A2 C-7
nan F7 A2 F7
nan nan A2 F7
nan F-7 A2 F-7
nan nan A2 F-7
nan Bb7 A2 Bb7
nan nan A2 Bb7
nan Ebj7 A2 Ebj7
nan nan A2 Ebj7
nan Eb-6 A2 Eb-6
nan nan A2 Eb-6
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan nan A2 Bbj7
nan nan A2 Bbj7
B1 D7 B1 D7
nan nan B1 D7
nan nan B1 D7
nan nan B1 D7
nan D7 B1 D7
nan nan B1 D7
nan nan B1 D7
nan nan B1 D7
nan G7 B1 G7
nan nan B1 G7
nan nan B1 G7
nan nan B1 G7
nan G7 B1 G7
nan nan B1 G7
nan nan B1 G7
nan nan B1 G7
nan C7 B1 C7
nan nan B1 C7
nan nan B1 C7
nan nan B1 C7
nan C7 B1 C7
nan nan B1 C7
nan nan B1 C7
nan nan B1 C7
nan F7 B1 F7
nan nan B1 F7
nan nan B1 F7
nan nan B1 F7
nan F7 B1 F7
nan nan B1 F7
nan nan B1 F7
nan nan B1 F7
A3 Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
nan Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
nan F-7 A3 F-7
nan nan A3 F-7
nan Bb7 A3 Bb7
nan nan A3 Bb7
nan Ebj7 A3 Ebj7
nan nan A3 Ebj7
nan Eb-6 A3 Eb-6
nan nan A3 Eb-6
nan Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
A1 Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
nan F-7 A1 F-7
nan nan A1 F-7
nan Bb7 A1 Bb7
nan nan A1 Bb7
nan Ebj7 A1 Ebj7
nan nan A1 Ebj7
nan Eb-6 A1 Eb-6
nan nan A1 Eb-6
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
A2 Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan C-7 A2 C-7
nan nan A2 C-7
nan F7 A2 F7
nan nan A2 F7
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan C-7 A2 C-7
nan nan A2 C-7
nan F7 A2 F7
nan nan A2 F7
nan nan A2 F7
nan nan A2 F7
nan Bb7 A2 Bb7
nan nan A2 Bb7
nan nan A2 Bb7
nan nan A2 Bb7
nan Eb-6 A2 Eb-6
nan nan A2 Eb-6
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan nan A2 Bbj7
nan nan A2 Bbj7
B1 D7 B1 D7
nan nan B1 D7
nan nan B1 D7
nan nan B1 D7
nan D7 B1 D7
nan nan B1 D7
nan nan B1 D7
nan nan B1 D7
nan G7 B1 G7
nan nan B1 G7
nan nan B1 G7
nan nan B1 G7
nan G7 B1 G7
nan nan B1 G7
nan nan B1 G7
nan nan B1 G7
nan C7 B1 C7
nan nan B1 C7
nan nan B1 C7
nan nan B1 C7
nan C7 B1 C7
nan nan B1 C7
nan nan B1 C7
nan nan B1 C7
nan F7 B1 F7
nan nan B1 F7
nan nan B1 F7
nan nan B1 F7
nan F7 B1 F7
nan nan B1 F7
nan nan B1 F7
nan nan B1 F7
A3 Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
nan Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
nan F-7 A3 F-7
nan nan A3 F-7
nan Bb7 A3 Bb7
nan nan A3 Bb7
nan Ebj7 A3 Ebj7
nan nan A3 Ebj7
nan Eb-6 A3 Eb-6
nan nan A3 Eb-6
nan Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
A1 Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
nan F-7 A1 F-7
nan nan A1 F-7
nan Bb7 A1 Bb7
nan nan A1 Bb7
nan Ebj7 A1 Ebj7
nan nan A1 Ebj7
nan Eb-6 A1 Eb-6
nan nan A1 Eb-6
nan Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7
A2 Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan C-7 A2 C-7
nan nan A2 C-7
nan F7 A2 F7
nan nan A2 F7
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan C-7 A2 C-7
nan nan A2 C-7
nan F7 A2 F7
nan nan A2 F7
nan F-7 A2 F-7
nan nan A2 F-7
nan Bb7 A2 Bb7
nan nan A2 Bb7
nan Ebj7 A2 Ebj7
nan nan A2 Ebj7
nan Eb-6 A2 Eb-6
nan nan A2 Eb-6
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan G7 A2 G7
nan nan A2 G7
nan Bbj7 A2 Bbj7
nan nan A2 Bbj7
nan nan A2 Bbj7
nan nan A2 Bbj7
B1 D7 B1 D7
nan nan B1 D7
nan nan B1 D7
nan nan B1 D7
nan D7 B1 D7
nan nan B1 D7
nan nan B1 D7
nan nan B1 D7
nan G7 B1 G7
nan nan B1 G7
nan nan B1 G7
nan nan B1 G7
nan G7 B1 G7
nan nan B1 G7
nan nan B1 G7
nan nan B1 G7
nan C7 B1 C7
nan nan B1 C7
nan nan B1 C7
nan nan B1 C7
nan C7 B1 C7
nan nan B1 C7
nan nan B1 C7
nan nan B1 C7
nan F7 B1 F7
nan nan B1 F7
nan nan B1 F7
nan nan B1 F7
nan F7 B1 F7
nan nan B1 F7
nan nan B1 F7
nan nan B1 F7
A3 Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
nan Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
nan F-7 A3 F-7
nan nan A3 F-7
nan Bb7 A3 Bb7
nan nan A3 Bb7
nan Ebj7 A3 Ebj7
nan nan A3 Ebj7
nan Eb-6 A3 Eb-6
nan nan A3 Eb-6
nan Bbj7 A3 Bbj7
nan nan A3 Bbj7
nan G7 A3 G7
nan nan A3 G7
nan C-7 A3 C-7
nan nan A3 C-7
nan F7 A3 F7
nan nan A3 F7
A1 Bbj7 A1 Bbj7
nan nan A1 Bbj7
nan G7 A1 G7
nan nan A1 G7
nan C-7 A1 C-7
nan nan A1 C-7
nan F7 A1 F7
nan nan A1 F7

In [111]:
chord_prog['Blue Train'] = {
    'section': sections_b,
    'progression': parts_b,
    "key": "Bb",
    "minor": False,
    "time_signature": [4,4]
}

In [113]:
chord_prog.keys()

dict_keys(['Margie', 'Oleo', 'Blue Train'])

In [116]:
json.dump(chord_prog, open('../data/chord_progression_sources/weimar_db.json', 'w+'))